export default {
  site: {
    title: 'Earthquake Zen Garden',
    heroImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Arenal_Volcano_07_2015_CRI_3828.jpg/1920px-Arenal_Volcano_07_2015_CRI_3828.jpg',
    logoImage: 'https://www.realtor.com/realtor-com.png',
  },
  profile: {
    firstName: 'Sally',
    lastName: 'Wang',
    avatarImage: 'https://upload.wikimedia.org/wikipedia/commons/5/59/That_Poppy_profile_picture.jpg',
    phone: '01-343-989-2345',
    email: 'sw@nowhere.ic.kp',
    bio:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
  },
  data: {
    type: 'FeatureCollection',
    metadata: {
      generated: 1523648330000,
      url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson',
      title: 'USGS All Earthquakes, Past Hour',
      status: 200,
      api: '1.5.8',
      count: 9,
    },
    features: [
      {
        type: 'Feature',
        properties: {
          mag: 1.19,
          place: '3km ENE of The Geysers, CA',
          time: 1523647508250,
          updated: 1523648041843,
          tz: -480,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/nc72999021',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc72999021.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'automatic',
          tsunami: 0,
          sig: 22,
          net: 'nc',
          code: '72999021',
          ids: ',nc72999021,',
          sources: ',nc,',
          types: ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
          nst: 12,
          dmin: 0.008595,
          rms: 0.04,
          gap: 68,
          magType: 'md',
          type: 'earthquake',
          title: 'M 1.2 - 3km ENE of The Geysers, CA',
        },
        geometry: {
          type: 'Point',
          coordinates: [-122.7304993, 38.7903328, 1.22],
        },
        id: 'nc72999021',
      },
      {
        type: 'Feature',
        properties: {
          mag: 0.54,
          place: '11km NE of Aguanga, CA',
          time: 1523647447080,
          updated: 1523648292169,
          tz: -480,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/ci38148464',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci38148464.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'reviewed',
          tsunami: 0,
          sig: 4,
          net: 'ci',
          code: '38148464',
          ids: ',ci38148464,',
          sources: ',ci,',
          types: ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
          nst: 19,
          dmin: 0.06726,
          rms: 0.11,
          gap: 47,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 0.5 - 11km NE of Aguanga, CA',
        },
        geometry: {
          type: 'Point',
          coordinates: [-116.7931667, 33.5168333, 5.69],
        },
        id: 'ci38148464',
      },
      {
        type: 'Feature',
        properties: {
          mag: 1.5,
          place: '65km W of Anchor Point, Alaska',
          time: 1523647111107,
          updated: 1523647975137,
          tz: -540,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/ak19233683',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak19233683.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'automatic',
          tsunami: 0,
          sig: 35,
          net: 'ak',
          code: '19233683',
          ids: ',ak19233683,',
          sources: ',ak,',
          types: ',geoserve,origin,',
          nst: null,
          dmin: null,
          rms: 0.76,
          gap: null,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 1.5 - 65km W of Anchor Point, Alaska',
        },
        geometry: {
          type: 'Point',
          coordinates: [-152.9665, 59.6595, 102.5],
        },
        id: 'ak19233683',
      },
      {
        type: 'Feature',
        properties: {
          mag: 2.3,
          place: '31km SE of Bridgeport, California',
          time: 1523646631530,
          updated: 1523646936090,
          tz: -480,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/nn00630289',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nn00630289.geojson',
          felt: 0,
          cdi: 0,
          mmi: null,
          alert: null,
          status: 'automatic',
          tsunami: 0,
          sig: 81,
          net: 'nn',
          code: '00630289',
          ids: ',nn00630289,',
          sources: ',nn,',
          types: ',dyfi,geoserve,origin,phase-data,',
          nst: 20,
          dmin: 1.109,
          rms: 0.19,
          gap: 129.72,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 2.3 - 31km SE of Bridgeport, California',
        },
        geometry: {
          type: 'Point',
          coordinates: [-118.9815, 38.0482, 13],
        },
        id: 'nn00630289',
      },
      {
        type: 'Feature',
        properties: {
          mag: 1.5,
          place: '13km NNW of Fritz Creek, Alaska',
          time: 1523646564971,
          updated: 1523647974895,
          tz: -540,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/ak19233673',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak19233673.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'automatic',
          tsunami: 0,
          sig: 35,
          net: 'ak',
          code: '19233673',
          ids: ',ak19233673,',
          sources: ',ak,',
          types: ',geoserve,origin,',
          nst: null,
          dmin: null,
          rms: 0.82,
          gap: null,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 1.5 - 13km NNW of Fritz Creek, Alaska',
        },
        geometry: {
          type: 'Point',
          coordinates: [-151.3919, 59.8471, 163.6],
        },
        id: 'ak19233673',
      },
      {
        type: 'Feature',
        properties: {
          mag: 5.3,
          place: '24km ESE of Nemuro, Japan',
          time: 1523646000170,
          updated: 1523647410040,
          tz: 540,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us2000dzwr',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us2000dzwr.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'reviewed',
          tsunami: 0,
          sig: 432,
          net: 'us',
          code: '2000dzwr',
          ids: ',us2000dzwr,',
          sources: ',us,',
          types: ',geoserve,origin,phase-data,',
          nst: null,
          dmin: 2.306,
          rms: 1.03,
          gap: 58,
          magType: 'mww',
          type: 'earthquake',
          title: 'M 5.3 - 24km ESE of Nemuro, Japan',
        },
        geometry: {
          type: 'Point',
          coordinates: [145.8313, 43.208, 42.74],
        },
        id: 'us2000dzwr',
      },
      {
        type: 'Feature',
        properties: {
          mag: 0.93,
          place: '10km NE of Aguanga, CA',
          time: 1523645864330,
          updated: 1523648313171,
          tz: -480,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/ci38148440',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci38148440.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'reviewed',
          tsunami: 0,
          sig: 13,
          net: 'ci',
          code: '38148440',
          ids: ',ci38148440,',
          sources: ',ci,',
          types: ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
          nst: 35,
          dmin: 0.07121,
          rms: 0.22,
          gap: 36,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 0.9 - 10km NE of Aguanga, CA',
        },
        geometry: {
          type: 'Point',
          coordinates: [-116.7943333, 33.5123333, 4.65],
        },
        id: 'ci38148440',
      },
      {
        type: 'Feature',
        properties: {
          mag: 1.6,
          place: '44km NNW of Valdez, Alaska',
          time: 1523645022880,
          updated: 1523645250368,
          tz: -540,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/ak19233602',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak19233602.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'automatic',
          tsunami: 0,
          sig: 39,
          net: 'ak',
          code: '19233602',
          ids: ',ak19233602,',
          sources: ',ak,',
          types: ',geoserve,origin,',
          nst: null,
          dmin: null,
          rms: 0.49,
          gap: null,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 1.6 - 44km NNW of Valdez, Alaska',
        },
        geometry: {
          type: 'Point',
          coordinates: [-146.6562, 61.497, 31],
        },
        id: 'ak19233602',
      },
      {
        type: 'Feature',
        properties: {
          mag: 1.6,
          place: '133km WSW of Ruby, Alaska',
          time: 1523644756560,
          updated: 1523645047293,
          tz: -540,
          url: 'https://earthquake.usgs.gov/earthquakes/eventpage/ak19233598',
          detail: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak19233598.geojson',
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: 'automatic',
          tsunami: 0,
          sig: 39,
          net: 'ak',
          code: '19233598',
          ids: ',ak19233598,',
          sources: ',ak,',
          types: ',geoserve,origin,',
          nst: null,
          dmin: null,
          rms: 0.6,
          gap: null,
          magType: 'ml',
          type: 'earthquake',
          title: 'M 1.6 - 133km WSW of Ruby, Alaska',
        },
        geometry: {
          type: 'Point',
          coordinates: [-158.1586, 64.3882, 6.9],
        },
        id: 'ak19233598',
      },
    ],
    bbox: [-158.1586, 33.5123333, 1.22, 145.8313, 64.3882, 163.6],
  },
};
